# Generated by Django 5.0.6 on 2024-05-20 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('locked', 'Locked')], default='active', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='acount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='acount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='acount',
        ),
        migrations.AddField(
            model_name='bill',
            name='Account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.account'),
        ),
        migrations.AddField(
            model_name='cart',
            name='Account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.account'),
        ),
        migrations.CreateModel(
            name='DetailAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('id_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='app.account')),
            ],
        ),
        migrations.DeleteModel(
            name='Detail_Acount',
        ),
        migrations.DeleteModel(
            name='Acount',
        ),
    ]
